all:
	python3 -m pip install --upgrade pip
	pip3 install tensorflow
	pip3 install keras
	pip3 install numpy
	python3 __main__.py

install:
	python3 -m pip install --upgrade pip
	pip3 install tensorflow
	pip3 install keras
	pip3 install numpy

app:
	python3 clasify.py

run:
	python3 __main__.py